### ISSUE TITLE
DBInstanceType AllowedPattern requires double quotes

### ISSUE THREAD

**Issue by aaronatbissell** [aws/aws-connected-device-framework#183]
**Aws Connected Device Framework Affected Module(s):**
 
assetlibrary

**I'm submitting a ...**

- [x] bug report
- [ ] feature request

**Description:**

Deployment fails because parameters passed in for DBInstanceType doesn't abide by AllowedPattern

**Current behavior:**

Deployment fails with DBInstanceTypes like `db.r5.large`

**Expected behavior:**

Deployment works with DBInstanceTypes like `db.r5.large`

**Steps to reproduce:**

* Pass a DBInstanceType like `db.r5.large` to the deploy function

**Additional Information:**
I recreated this with a minimal cloudformation:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Test Stack

Parameters:
  Tester:
    Description: Just for a test
    Type: String
    AllowedPattern: '^db\\.[tr]\\d+[a-z0-9]*\\.[a-z0-9]*$'

Resources:
  HelloBucket:
    Type: 'AWS::S3::Bucket'
```

Trying to deploy this with the following command gives me an error:

```bash
aws cloudformation deploy --template-file template.yml --stack-name test-stack --parameter-overrides Tester=db.r5.large
```

`An error occurred (ValidationError) when calling the CreateChangeSet operation: Parameter 'Tester' must match pattern ^db\\.[tr]\\d+[a-z0-9]*\\.[a-z0-9]*$`

Changing this to be double quotes yields a proper stack deployment:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Test Stack

Parameters:
  Tester:
    Description: Just for a test
    Type: String
    AllowedPattern: "^db\\.[tr]\\d+[a-z0-9]*\\.[a-z0-9]*$"

Resources:
  HelloBucket:
    Type: 'AWS::S3::Bucket'
```

```bash
aws cloudformation deploy --template-file template.yml --stack-name test-stack --parameter-overrides Tester=db.r5.large
```

`Waiting for changeset to be created..`
`Waiting for stack create/update to complete`
`Successfully created/updated stack - test-stack`
