### ISSUE TITLE
authorization error on iot:RegisterCertificateWithoutCA of cdf-provisioning

### ISSUE THREAD

**Issue by aiasmartakis** [aws/aws-connected-device-framework#36]
**Aws Connected Device Framework Affected Module(s):**
 
cdf-provisioning

**I'm submitting a ...**

- [x ] bug report
- [ ] feature request

**Description:**

An iot:RegisterCertificateWithoutCA on resource error is thrown due to restrictive policy in cfn-provisioning.yml when triggering bulkprovisioning through s3 events that execute a lambda (in the facade).

**Current behavior:**
Error: "error\\":\\"User: arn:aws:sts::876972130410:assumed-role/cdf-provisioning-development-LambdaExecutionRole-1O132CZTTSXBM/cdf-provisioning-rest-development is not authorized to perform: iot:RegisterCertificateWithoutCA on resource: * because no identity-based policy allows the iot:RegisterCertificateWithoutCA action

**Expected behavior:**
AWS IoT things created through bulk-provisioning.

**Steps to reproduce:**
-setup s3 prefix with event that triggers a call to a lambda.
-lambda to read the file and lambda invoke cdf-provision:
                    response = lambda_invoke(
                        function=PROVISIONLAMBDA,
                        path='/things',
                        method='POST',
                        headers=HEADERS,
                        query_string_params=None,
                        stage_variables=None,
                        request_context=None,
                        body=build_payload(dev_id, certificate)
                    )
**Additional Information:**
a very permissive policy in cfn-provisioning.yml allows this to work:
```
  BulkProvisioningPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "cdf-provisioning policy for enabling bulk provisoning"
      Path: "/cdf/provisioning/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - 'iam:PassRole'
            Effect: Allow
            Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/cdf-provisioning-*"
          - Action:
              - 'iot:RegisterCertificateWithoutCA'
            Effect: Allow
            Resource: "*"
```
I tried, something more restrictive which doesn't:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "iam:PassRole"
            ],
            "Resource": "arn:aws:iam::ACCOUNT_ID:role/cdf-provisioning-*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "iot:RegisterCertificateWithoutCA"
            ],
            "Resource": [
                "arn:aws:iot:us-west-2:ACCOUNT_ID:*",
                "arn:aws:lambda:us-west-2:ACCOUNT_ID:*",
                "arn:aws:s3:::cdfdevreg-us-west-2-ACCOUNT_ID/shortfiles/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

```
2021-11-24T17:33:59.919Z error: User: arn:aws:sts::ACCOUNT_ID:assumed-role/cdf-provisioning-LambdaExecutionRole/cdf-provisioning-rest-development is not authorized to perform: iot:RegisterCertificateWithoutCA on resource: * because no identity-based policy allows the iot:RegisterCertificateWithoutCA action
--
2021-11-24T17:33:59.919Z error: handleError: AccessDeniedException: User: arn:aws:sts::ACCOUNT_ID:assumed-role/cdf-provisioning-development-LambdaExecutionRole/cdf-provisioning-rest-development is not authorized to perform: ot:RegisterCertificateWithoutCA on resource: * because no identity-based policy allows the iot:RegisterCertificateWithoutCA action
2021-11-24T17:33:59.922Z error: handleError: res.status: function status(code) {
this.statusCode = code;
return this;
}
```
